import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { getStoredRepositories } from "@/lib/storage";
import type { Repository } from "@/lib/types";

interface ReportDownloadProps {
  repoId: string;
  repoName: string;
  repo?: Repository;
}

function bar(value: number, max: number = 10, width: number = 20): string {
  const filled = Math.round((value / max) * width);
  return "█".repeat(filled) + "░".repeat(width - filled);
}

function generateMarkdownReport(r: Repository): string {
  const scoreColor = (s: number) => (s >= 7 ? "🟢" : s >= 5 ? "🟡" : "🔴");
  const checkMark = (b?: boolean) => (b ? "✅" : "❌");

  return `# RepoInsight Executive Health Report
## ${r.owner}/${r.repo_name}

**Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
**Repository:** ${r.repo_url}
**Language:** ${r.language || "Unknown"}
**Description:** ${r.description || "No description provided"}

---

## Overall Quality Score: ${Number(r.score).toFixed(1)}/10 ${scoreColor(Number(r.score))}

${bar(Number(r.score))} ${Number(r.score).toFixed(1)}/10

---

## Quality Score Breakdown

| Category | Score | Rating |
|----------|-------|--------|
| Documentation | ${Number(r.documentation_score).toFixed(1)}/10 | ${scoreColor(Number(r.documentation_score))} |
| Maintainability | ${Number(r.maintainability_score).toFixed(1)}/10 | ${scoreColor(Number(r.maintainability_score))} |
| Structure | ${Number(r.structure_score).toFixed(1)}/10 | ${scoreColor(Number(r.structure_score))} |
| Community Health | ${Number(r.community_health_score || 0).toFixed(1)}/10 | ${scoreColor(Number(r.community_health_score || 0))} |
| Activity | ${Number(r.activity_score || 0).toFixed(1)}/10 | ${scoreColor(Number(r.activity_score || 0))} |
| Dependency Health | ${Number(r.dependency_health_score || 0).toFixed(1)}/10 | ${scoreColor(Number(r.dependency_health_score || 0))} |
| Code Complexity | ${Number(r.code_complexity_score || 0).toFixed(1)}/10 | ${scoreColor(Number(r.code_complexity_score || 0))} |

---

## Risk Prediction Assessment

**Risk Score:** ${Number(r.risk_score || 1.0).toFixed(1)}/10
**Risk Level:** ${r.risk_level || "Low"}

### Identified Indicators:
${(r.risk_reasons || ["No significant risk indicators detected"]).map((reason) => `- ${reason}`).join("\n")}

---

## Key Repository Metrics

| Metric | Value |
|--------|-------|
| ⭐ Stars | ${Number(r.stars || 0).toLocaleString()} |
| 🍴 Forks | ${Number(r.forks || 0).toLocaleString()} |
| 🐛 Open Issues | ${Number(r.issues || 0).toLocaleString()} |
| 👁 Watchers | ${Number(r.watchers || 0).toLocaleString()} |
| 👥 Contributors | ~${Number(r.contributors || 1).toLocaleString()} |
| 📁 Files | ${Number(r.file_count || 0).toLocaleString()} |
| 📊 Avg File Size | ${Number(r.avg_file_size || 0).toLocaleString()} bytes |
| ⚠️ Large Files (>50KB) | ${r.large_files_count || 0} |
| 📐 Max Directory Depth | ${r.max_directory_depth || 0} |
| 📦 Dependencies | ${r.dependency_count || 0} |
| 🔒 Dependency Risk | ${r.dependency_risk_level || "Low"} |
| 🔄 Commit Frequency | ${r.commit_frequency || "unknown"} |
| 📅 Last Commit | ${r.last_commit_date ? new Date(r.last_commit_date).toLocaleDateString() : "Unknown"} |

---

## Health & Quality Indicators

| Indicator | Status |
|-----------|--------|
| Tests Suite | ${checkMark(r.has_tests)} |
| CI/CD Pipeline | ${checkMark(r.has_ci_cd)} |
| Documentation Folder | ${checkMark(r.has_docs_folder)} |
| Contributing Guide | ${checkMark(r.has_contributing)} |
| License File | ${checkMark(r.has_license)} |

---

## Technology Stack Detected

${(r.detected_technologies || []).map((t) => `- ${t}`).join("\n") || "No technologies detected"}

---

## Dependency Files

${(r.dependency_files || []).map((f) => `- ${f}`).join("\n") || "No dependency files detected"}

---

## AI Analysis Summary

${r.summary || "Analysis complete."}

${r.explanation?.score_explanation ? `\n### Score Explanation\n${r.explanation.score_explanation}\n` : ""}

---

## Architectural Insights

${r.explanation?.purpose ? `**Purpose:** ${r.explanation.purpose}\n` : ""}
${r.explanation?.architecture ? `**Architecture:** ${r.explanation.architecture}\n` : ""}
${r.explanation?.key_modules?.length ? `**Key Modules:** ${r.explanation.key_modules.join(", ")}\n` : ""}
${r.explanation?.how_to_run ? `**How to Run:** ${r.explanation.how_to_run}\n` : ""}

---

## Actionable Recommendations

${(r.recommendations || []).map((rec, i) => `${i + 1}. ${rec}`).join("\n") || "No recommendations."}

---

*Generated by RepoInsight — AI GitHub Repository Intelligence Platform*
`;
}

export default function ReportDownload({ repoId, repoName, repo }: ReportDownloadProps) {
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const handleDownload = async () => {
    setLoading(true);
    let markdownContent = "";
    let downloadFileName = `${repoName}-health-report.md`;

    try {
      // 1. Try Supabase edge function first if online
      const { data, error } = await supabase.functions.invoke("generate-report", {
        body: { repo_id: repoId },
      });
      if (!error && data?.markdown) {
        markdownContent = data.markdown;
        if (data.filename) downloadFileName = data.filename;
      }
    } catch {
      // Fallback
    }

    // 2. Client-side fallback if edge function unavailable
    if (!markdownContent) {
      let targetRepo = repo;
      if (!targetRepo) {
        const stored = getStoredRepositories();
        targetRepo = stored.find((r) => r.id === repoId || `${r.owner}-${r.repo_name}` === repoName || r.repo_name === repoName);
      }
      if (targetRepo) {
        markdownContent = generateMarkdownReport(targetRepo);
      }
    }

    if (markdownContent) {
      const blob = new Blob([markdownContent], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = downloadFileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({ title: "Report downloaded!", description: `${downloadFileName} saved successfully.` });
    } else {
      toast({ title: "Download failed", description: "Report data unavailable.", variant: "destructive" });
    }

    setLoading(false);
  };

  return (
    <Button onClick={handleDownload} disabled={loading} variant="outline" size="sm" className="gap-2">
      {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
      Download Report
    </Button>
  );
}
